<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.2">
  <POU Name="MAIN" Id="{c2b5ef02-c814-43e4-afb8-0f2b009686dc}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
  nTest: INT;
  sTest: STRING;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>